### ISSUE TITLE
How to reverse up and down menu?

### ISSUE THREAD

**Issue by StackHelp** [Kharauzov/SwipeableCards#1]
I have tried to reverse things but I failed miserably. Like, swipe down to open the menu and to swipe up to dismiss cell. Can you help me pls?

**Comment by Kharauzov** [comment]
Hi @StackHelp , could you clarify your question?

**Comment by StackHelp** [comment]
I want to drag a top part to open a menu and on the drag from bottom to up, want to remove the collection cell.
![thumbnail](https://user-images.githubusercontent.com/41230403/77722820-c7163680-7014-11ea-8524-11d541e6cba5.jpg)
![thumbnail1](https://user-images.githubusercontent.com/41230403/77722826-ca112700-7014-11ea-8cbb-d1f48a33cb57.jpg)

**Comment by Kharauzov** [comment]
@StackHelp , based on your screenshots I see, that you're implementing this functional for Android OS, so you must be using Java or Kotlin for this purpose.
I don't have much experience in those areas, so not sure, that I can help you with this..
I would suggest providing your questions to someone experienced with Android and custom interfaces.

**Comment by StackHelp** [comment]
No No. This is the screenshot of android but I need same kind of functionality and I found similar kind of thing in Swipable Cards but here I want menu to be opened from top and not from bottom and on drag up, delete collection cell.

**Comment by Kharauzov** [comment]
@StackHelp , I don't understand you. Are you going to implement it for iOS using Swift?

**Comment by StackHelp** [comment]
Yes, I want to implement it for iOS using Swift and takes inspiration from your project but I am not succeded yet for this

**Comment by Kharauzov** [comment]
@StackHelp , okay, in this case, I propose you to provide some specific questions. Maybe referencing to the code in my project, so that I can see, what doesn't work for you and what you tried.
Otherwise, your current questions are just generalized.
